services:
  app:
    image: boilerplate:dev
    secrets:
      - db_password
      - redis_password
      - smtp_password
      - access_token_secret
      - refresh_token_secret
      - csrf_secret
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      SMTP_PASSWORD_FILE: /run/secrets/smtp_password
      ACCESS_TOKEN_SECRET_FILE: /run/secrets/access_token_secret
      REFRESH_TOKEN_SECRET_FILE: /run/secrets/refresh_token_secret
      CSRF_SECRET_FILE: /run/secrets/csrf_secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    image: postgres:17.6-alpine
    secrets:
      - db_password
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  
  redis:
    image: redis:7.2.10-alpine
    secrets:
      - redis_acl
      - redis_password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "healthcheck", "--pass", "", "--no-auth-warning", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes", "--aclfile", "/run/secrets/redis_acl"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  sqitch:
    image: gregorylaigneau/sqitch:0.0.1
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep infinity"]
    environment:
      PGUSER: ${PG_USERNAME}
      PGHOST: ${PG_HOST}
      PGDATABASE: ${PG_NAME}
      PGPORT: ${PG_PORT}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    configs:
      - source: sqitch_config
        target: /app/sqitch.conf
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: overlay
    attachable: true

configs:
  sqitch_config:
    file: ./sqitch.conf

secrets:
  db_password:
    file: ./secrets/db_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  smtp_password:
    file: ./secrets/smtp_password.txt
  redis_acl:
    file: ./secrets/redis_acl.txt
  access_token_secret:
    file: ./secrets/access_token_secret.txt
  refresh_token_secret:
    file: ./secrets/refresh_token_secret.txt
  csrf_secret:
    file: ./secrets/csrf_secret.txt