FROM sqitch/sqitch:v1.6.0

WORKDIR /app

USER sqitch

COPY --chown=sqitch:sqitch database/migrations /app/database/migrations

USER root

COPY scripts/*.sh /usr/local/bin/
COPY scripts/utils/*.sh /usr/local/bin/utils/
RUN chmod +x /usr/local/bin/*.sh /usr/local/bin/utils/*.sh

USER sqitch