import {
  ACCESS_TOKEN_EXPIRY_MINUTES,
  ACCESS_TOKEN_SECRET,
  ACTIVATION_TOKEN_EXPIRY_MINUTES,
  CSRF_SECRET,
  REFRESH_TOKEN_EXPIRY_DAYS,
  REFRESH_TOKEN_SECRET,
  RESET_PASSWORD_TOKEN_EXPIRY_MINUTES,
} from "#config/envConfig.mjs";

import { MS_IN_ONE_DAY, MS_IN_ONE_MINUTE } from "#constants/timeConstant.mjs";

export { ACCESS_TOKEN_SECRET, CSRF_SECRET, REFRESH_TOKEN_SECRET };

export const ACCESS_TOKEN_EXPIRES_IN = `${ACCESS_TOKEN_EXPIRY_MINUTES}m`;
export const ACCESS_TOKEN_MAX_AGE = ACCESS_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE;

export const REFRESH_TOKEN_EXPIRES_IN = `${REFRESH_TOKEN_EXPIRY_DAYS}d`;
export const REFRESH_TOKEN_MAX_AGE = REFRESH_TOKEN_EXPIRY_DAYS * MS_IN_ONE_DAY;
export const REFRESH_TOKEN_LIFETIME_MS = REFRESH_TOKEN_MAX_AGE;

export const ACTIVATION_TOKEN_EXPIRY_MS = ACTIVATION_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE;
export const RESET_PASSWORD_TOKEN_EXPIRY_MS = RESET_PASSWORD_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE;
