import { SECURITY_ENV, TOKEN_ENV } from "#config/envConfig.mjs";
import { MS_IN_ONE_DAY, MS_IN_ONE_MINUTE } from "#constants/timeConstant.mjs";

const {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY_MINUTES,
  REFRESH_TOKEN_EXPIRY_DAYS,
  ACTIVATION_TOKEN_EXPIRY_MINUTES,
  RESET_PASSWORD_TOKEN_EXPIRY_MINUTES,
} = TOKEN_ENV;

const { CSRF_SECRET } = SECURITY_ENV;

export const TOKEN_CONFIG = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  CSRF_SECRET,
  ACCESS_TOKEN_EXPIRES_IN: `${ACCESS_TOKEN_EXPIRY_MINUTES}m`,
  ACCESS_TOKEN_MAX_AGE: ACCESS_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE,
  REFRESH_TOKEN_EXPIRES_IN: `${REFRESH_TOKEN_EXPIRY_DAYS}d`,
  REFRESH_TOKEN_MAX_AGE: REFRESH_TOKEN_EXPIRY_DAYS * MS_IN_ONE_DAY,
  REFRESH_TOKEN_LIFETIME_MS: REFRESH_TOKEN_EXPIRY_DAYS * MS_IN_ONE_DAY,
  ACTIVATION_TOKEN_EXPIRY_MS: ACTIVATION_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE,
  RESET_PASSWORD_TOKEN_EXPIRY_MS: RESET_PASSWORD_TOKEN_EXPIRY_MINUTES * MS_IN_ONE_MINUTE,
};
